apiVersion: v1
kind: Service
metadata:
  name: testflow
  namespace: namespace-workflow-1709639770486
spec:
  type: LoadBalancer
  selector:
    app: testflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000